<a href="https://colab.research.google.com/github/mkh-ai/Complete-Python-3-Bootcamp/blob/master/array_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
data1 = [1,2,3,4]
arr1 = np.array(data1)


In [4]:
arr1

array([1, 2, 3, 4])

In [5]:
data2 = (5,6,7,8)
arr2= np.array(data2)


In [8]:
arr2.ndim    # arr2 ning olchami


1

**Ikki va undan yuqori bolgan massivlar**

In [11]:
data3 = [[1,2,3,4,5],[6,7,8,9]]
arr3 = np.array(data3)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  


In [15]:
data4 = [[1,2,3,4],[5,6,7,8,],[9,10,11,12]]   # 3 olchamli massiv
arr4 = np.array(data4)


In [18]:
arr4.ndim



2

# shape va sisze metodlari

In [19]:
arr4.shape  # masssivning qator va ustunlarini sonini korsatadi




(3, 4)

In [20]:
arr4.size   # massiv olchamini chiqaradi

12

# N olchamli massiv yaratishning boshqa usullarni


**zeros va ones funksiyalari** 

In [22]:
arr5 = np.zeros((3,4))  # barcha elementlari 0 ga teng massiv yaratadi
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
arr6 = np.ones((5,8))   # barcha elementlari 1 ga teng massiv yaratadi
arr6

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

**arange funksiyasi yordanida yaratish**

In [25]:
arr7 = np.arange(34,500,30)  # 30 qadam bilan massiv yaratdi
arr7

array([ 34,  64,  94, 124, 154, 184, 214, 244, 274, 304, 334, 364, 394,
       424, 454, 484])